name: BloodNight
description: Make your nights a nightmare again
author: Racci
version: ${version}
main: me.racci.bloodnight.core.BloodNight
api-version: 1.17
depend: [ RacciCore, EcoEnchants ]
softdepend:
  - Multiverse-Core
  - PlaceholderAPI

commands:
  bloodnight:
    description: Main Blood Night command.
    usage: "/bloodnight help"
    aliases:
      - bnight
      - bn
